# config/os1_middle_right.param.yaml
---

lidar_middle_right:
  os1_driver_node:
    ros__parameters:
      default_config: False
      udp_sensor_ip: "192.168.1.72"
      udp_computer_ip: "192.168.1.100"
      udp_port_lidar: "7506"
      udp_port_imu: "7507"
      lidar_mode: "1024x10"
      generation: "Gen2"

      #udp_driver
      ip: "192.168.1.100"
      port: 7506
      topic: "points"
      # 1024*64=65536
      cloud_size:  355000
      frame_id: "lidar_middle_right/os_lidar"
