# config/os1_test.param.yaml
---

lidar_top:
  os1_driver_node:
    ros__parameters:
      default_config: False
      udp_sensor_ip: "192.168.1.80"
      udp_computer_ip: "192.168.1.100"
      udp_port_lidar: "7508"
      udp_port_imu: "7509"
      lidar_mode: "1024x10"
      generation: "Gen2"

      #udp_driver
      ip: "192.168.1.100"
      port: 7508
      topic: "points"
      # 1024*64=65536
      cloud_size:  355000
      frame_id: "lidar_top/os_lidar"
