# config/os1_test.param.yaml
---

lidar_middle_left:
  os1_driver_node:
    ros__parameters:
      default_config: False
      udp_sensor_ip: "192.168.1.73"
      udp_computer_ip: "192.168.1.100"
      udp_port_lidar: "7504"
      udp_port_imu: "7505"
      lidar_mode: "2048x10"
      generation: "Gen2"

      #udp_driver
      ip: "192.168.1.100"
      port: 7504
      topic: "points"
      # 1024*64=65536
      cloud_size:  66000
      frame_id: "base_link"
